export default {
    GET_ALL_POKES_REQUESTED: 'GET_ALL_POKES_REQUESTED',
    GET_ALL_POKES_SUCCESS: 'GET_ALL_POKES_SUCCESS',
    GET_ALL_POKES_FAILURE: 'GET_ALL_POKES_FAILURE',   
    GET_POKE_REQUESTED: 'GET_POKE_REQUESTED',
    GET_POKE_SUCCESS: 'GET_POKE_SUCCESS',
    GET_POKE_FAILURE: 'GET_POKE_FAILURE',
    GET_POKE_IMAGE: 'GET_POKE_IMAGE',
}